spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates tables
    show-sql: true

server:
  port: 8080